version: '2'

volumes:
  mysql-data:

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - mysql.env
  web:
    build: ./dockerfiles/php5-apache2
    # build: ./dockerfiles/hhvm-nginx
    ports:
      - 80:8080
    volumes:
      - ./volumes/site:/var/www/site
    env_file:
      - mysql.env
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_autostart=1 remote_host=${DOCKERHOST}"
